language: python
python:
        - "2.7"
install:
        - pip install coverage
        - pip install coverage-badge
script: 
        - python -m coverage run test_rpn.py
        - python -m coverage report
        - python -m coverage_badge -o coverage.svg
